### ISSUE TITLE
Error in training with DDP mode

### ISSUE THREAD

**Issue by Lin-Qingyang-Alec** [DearCaat/PicT#1]
When I train PicT with DDP mode, I find this error:
File "main.py", line 207, in main
        models['main'] = NativeDDP(models['main'], device_ids=[config.LOCAL_RANK ])  # can use device str in Torch >= 1.1models['main'] = NativeDDP(models['main'], device_ids=[config.LOCAL_RANK ])  # can use device str in Torch >= 1.1
File "/eto_cn1/miniconda3/envs/XXX/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1659484657607/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
        return dist._verify_params_across_processes(process_group, tensors, logger)return dist._verify_params_across_processes(process_group, tensors, logger)

Wish to get your reply

**Comment by DearCaat** [comment]
If u use this launch script
`CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch --nproc_per_node=2`
this code work well in my test (torch 1.10.1+cu113, two 2080 Ti).
If u want to use the `torchrun`, please follow the https://pytorch.org/docs/stable/elastic/run.html#launcher-api to change the code.
I also find some talks about this error 
https://discuss.pytorch.org/t/runtimeerror-nccl-error-in-opt-conda-conda-bld-pytorch-1614378083779-work-torch-lib-c10d-processgroupnccl-cpp-825-unhandled-system-error-nccl-version-2-7-8/116129
https://discuss.pytorch.org/t/ncclinvalidusage-of-torch-nn-parallel-distributeddataparallel/133183
I hope this answer can help u, good luck
